require "ncurses"

require "./ncurses/constants"
require "./ncurses/helpers/types"
require "./ncurses/helpers/window"
require "./ncurses/draw"
require "./ncurses/display"
require "./ncurses/mixins/alignments"
require "./ncurses/mixins/justifications"
require "./ncurses/mixins/converters"
require "./ncurses/mixins/borders"
require "./ncurses/mixins/focusable"
require "./ncurses/mixins/bindings"
require "./ncurses/mixins/exit_conditions"
require "./ncurses/mixins/has_screen"
require "./ncurses/mixins/has_title"
require "./ncurses/mixins/common_controls"
require "./ncurses/mixins/formattable"
require "./ncurses/mixins/list_support"
require "./ncurses/mixins/movement"
require "./ncurses/mixins/window_hooks"
require "./ncurses/mixins/window_input"
require "./ncurses/crt_objs"
require "./ncurses/screen"
require "./ncurses/framing"
require "./ncurses/formatter"
require "./ncurses/components/label"
require "./ncurses/components/dialog"
require "./ncurses/components/entry"
require "./ncurses/components/scroller"
require "./ncurses/components/scroll"
require "./ncurses/components/button"
require "./ncurses/components/scale"
require "./ncurses/components/radio"
require "./ncurses/components/slider"
require "./ncurses/components/histogram"
require "./ncurses/components/item_list"
require "./ncurses/components/selection"
require "./ncurses/components/multi_entry"
require "./ncurses/components/template"
require "./ncurses/components/button_box"
require "./ncurses/components/calendar"
require "./ncurses/components/graph"
require "./ncurses/components/marquee"
require "./ncurses/components/scroll_window"
require "./ncurses/components/viewer"
require "./ncurses/components/menu"
require "./ncurses/components/alpha_list"
require "./ncurses/components/file_select"
require "./ncurses/components/matrix"

module CRT::Ncurses
  VERSION = "0.6.0"

  ALL_SCREENS = [] of CRT::Ncurses::Screen
  ALL_OBJECTS = [] of CRT::Ncurses::CRTObjs
end
