require "ncurses"

require "./cdk/constants"
require "./cdk/helpers/types"
require "./cdk/helpers/window"
require "./cdk/draw"
require "./cdk/display"
require "./cdk/mixins/alignments"
require "./cdk/mixins/justifications"
require "./cdk/mixins/converters"
require "./cdk/mixins/borders"
require "./cdk/mixins/focusable"
require "./cdk/mixins/bindings"
require "./cdk/mixins/exit_conditions"
require "./cdk/mixins/has_screen"
require "./cdk/mixins/has_title"
require "./cdk/mixins/common_controls"
require "./cdk/mixins/formattable"
require "./cdk/mixins/list_support"
require "./cdk/mixins/movement"
require "./cdk/mixins/window_hooks"
require "./cdk/mixins/window_input"
require "./cdk/cdk_objs"
require "./cdk/screen"
require "./cdk/components/label"
require "./cdk/components/dialog"
require "./cdk/components/entry"
require "./cdk/components/scroller"
require "./cdk/components/scroll"
require "./cdk/components/button"
require "./cdk/components/scale"
require "./cdk/components/radio"
require "./cdk/components/slider"
require "./cdk/components/histogram"
require "./cdk/components/itemlist"
require "./cdk/components/selection"
require "./cdk/components/mentry"
require "./cdk/components/template"
require "./cdk/components/fscale"
require "./cdk/components/dscale"
require "./cdk/components/uscale"
require "./cdk/components/fslider"
require "./cdk/components/uslider"
require "./cdk/components/buttonbox"
require "./cdk/components/calendar"
require "./cdk/components/graph"
require "./cdk/components/marquee"
require "./cdk/components/swindow"
require "./cdk/components/viewer"
require "./cdk/components/menu"
require "./cdk/components/alphalist"
require "./cdk/components/fselect"
require "./cdk/components/matrix"

module CDK
  VERSION = "0.1.0"

  ALL_SCREENS = [] of CDK::Screen
  ALL_OBJECTS = [] of CDK::CDKObjs
end
