require "ncurses"

require "./crt/constants"
require "./crt/helpers/types"
require "./crt/helpers/window"
require "./crt/draw"
require "./crt/display"
require "./crt/mixins/alignments"
require "./crt/mixins/justifications"
require "./crt/mixins/converters"
require "./crt/mixins/borders"
require "./crt/mixins/focusable"
require "./crt/mixins/bindings"
require "./crt/mixins/exit_conditions"
require "./crt/mixins/has_screen"
require "./crt/mixins/has_title"
require "./crt/mixins/common_controls"
require "./crt/mixins/formattable"
require "./crt/mixins/list_support"
require "./crt/mixins/movement"
require "./crt/mixins/window_hooks"
require "./crt/mixins/window_input"
require "./crt/crt_objs"
require "./crt/screen"
require "./crt/components/label"
require "./crt/components/dialog"
require "./crt/components/entry"
require "./crt/components/scroller"
require "./crt/components/scroll"
require "./crt/components/button"
require "./crt/components/scale"
require "./crt/components/radio"
require "./crt/components/slider"
require "./crt/components/histogram"
require "./crt/components/item_list"
require "./crt/components/selection"
require "./crt/components/multi_entry"
require "./crt/components/template"
require "./crt/components/button_box"
require "./crt/components/calendar"
require "./crt/components/graph"
require "./crt/components/marquee"
require "./crt/components/scroll_window"
require "./crt/components/viewer"
require "./crt/components/menu"
require "./crt/components/alpha_list"
require "./crt/components/file_select"
require "./crt/components/matrix"

module CRT
  VERSION = "0.2.0"

  ALL_SCREENS = [] of CRT::Screen
  ALL_OBJECTS = [] of CRT::CRTObjs
end
